### ISSUE TITLE
 Read error: #<ArgumentError: wrong number of arguments (2 for 1)> 

### ISSUE THREAD

**Issue by superfeedr** [carlosparamio/rack-facebook#2] opened 2010-08-25 15:55 UTC
Here is what I'm trying to run : http://gist.github.com/549765

But your Rack middleware fails :

```
    [2010-08-25 17:54:41] ERROR ArgumentError: wrong number of arguments (2 for 1)
/opt/local/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/builder.rb:54:in `initialize'
/opt/local/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/builder.rb:54:in `new'
/opt/local/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/builder.rb:54:in `use'
/opt/local/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/builder.rb:73:in `call'
/opt/local/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/builder.rb:73:in `to_app'
/opt/local/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:970:in `inject'
/opt/local/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/builder.rb:73:in `each'
/opt/local/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/builder.rb:73:in `inject'
/opt/local/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/builder.rb:73:in `to_app'
/opt/local/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:975:in `new'
/opt/local/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:960:in `prototype'
/opt/local/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'
/opt/local/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:1005:in `synchronize'
/opt/local/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'
/opt/local/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
/opt/local/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/handler/webrick.rb:52:in `service'
/opt/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/opt/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/opt/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/opt/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/opt/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/opt/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/opt/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/opt/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/opt/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/opt/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
/opt/local/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/handler/webrick.rb:13:in `run'
/opt/local/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:946:in `run!'
/opt/local/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/main.rb:25
app.rb:14
```

It would be cool to at least have 1 example in the repo :/

**Comment by carlosparamio** [comment] 2010-08-25 18:05
Hi there,

I've tried the code you've sent me with rack 1.2.1 and sinatra 1.0, and it seems to work fine: When I curl with unproper signed parameters to the POST action, it returns a 400 Bad Request with the body "Invalid Facebook signature". I don't have any canvas app ready right now to try it with properly signed facebook parameters, to see if it pass the conditions and executes the Sinatra action, but I suspect what you're suffering is not related to the gem (I can't see any call done from rack/facebook.rb at your backtrace).

There is one basic example on the README.markdown file. Actually, you don't need to do more than configure your application at Facebook so it redirects all the canvas requests to your application, and include a line as you did to indicate you want to use the rack/facebook middleware (you might want to avoid the middleware execution for some public routes; in that case, you have to add a block that returns true or false, depending of if you want the middleware to check the Facebook params signature).

Hope this helps!

**Comment by carlosparamio** [comment] 2010-08-25 18:09
Also, have you checked the link to the blog post that appears at the header of the project on github? It contains a more detailed explanation about how it works:

http://h1labs.com/notebook/2009/1/9/rack-facebook-a-new-rack-middleware-to-parse-facebook-parameters

**Comment by carlosparamio** [comment] 2010-09-02 10:28
Closing because lack of answer and reproducibility.

**Closed as completed by carlosparamio** 2010-09-02 10:28 UTC
